# Generated by Django 3.2 on 2021-04-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_group_app', '0003_auto_20210427_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameactive',
            old_name='game_Name',
            new_name='game_name',
        ),
    ]
